-- MySQL Script generated by MySQL Workbench
-- Sun Dec 22 22:36:57 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LandscapeCollector
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema LandscapeCollector
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LandscapeCollector` DEFAULT CHARACTER SET utf8 ;
USE `LandscapeCollector` ;

-- -----------------------------------------------------
-- Table `LandscapeCollector`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LandscapeCollector`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL DEFAULT 'null',
  `password` VARCHAR(45) NOT NULL DEFAULT 'null',
  `image` VARCHAR(45) NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LandscapeCollector`.`record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LandscapeCollector`.`record` (
  `idrecord` INT NOT NULL AUTO_INCREMENT,
  `iduser` INT NOT NULL,
  `country` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `picture` VARCHAR(45) NULL,
  `comment` VARCHAR(45) NULL,
  `star` INT NULL,
  PRIMARY KEY (`idrecord`),
  INDEX `fk_record_user_idx` (`iduser` ASC) ,
  CONSTRAINT `fk_record_user`
    FOREIGN KEY (`iduser`)
    REFERENCES `LandscapeCollector`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LandscapeCollector`.`collection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LandscapeCollector`.`collection` (
  `userid` INT NOT NULL,
  `recordid` INT NOT NULL,
  PRIMARY KEY (`userid`, `recordid`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
